"""Add new columns to ChatMessage

Revision ID: c795cb136d3e
Revises: 
Create Date: 2024-09-20 17:13:36.061176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c795cb136d3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generation_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tokens_prompt', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tokens_completion', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_column('total_cost')
        batch_op.drop_column('tokens_completion')
        batch_op.drop_column('tokens_prompt')
        batch_op.drop_column('generation_id')

    # ### end Alembic commands ###
