"""Add image_data to ChatMessage

Revision ID: fa1090a0210a
Revises: 
Create Date: 2024-09-23 17:13:01.707751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1090a0210a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('image_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_message', 'image_data')
    # ### end Alembic commands ###
